[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Prevent mixed content errors
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

# Handles direct routes to pages
[[redirects]]
  from = "/*"
  to = "/_next/static/chunks/pages%params.html"
  status = 200

# For Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
